### ISSUE TITLE
"gen_links.py" error

### ISSUE THREAD

**Issue by mxochicale** [rodluger/corTeX#6]
Repo has been cloned then tried : `corTeX/tex$ make` results in  

```
# Generate links to current git commit
python gen_links.py
  File "gen_links.py", line 6
    print(r"\newcommand{\codelink}[1]{\href{https://github.com/%s/blob/%s/tex/figures/#1.py}{\codeicon}\,\,}" % (slug, hash), file=f)
                                                                                                                                  ^
SyntaxError: invalid syntax
```

Any suggestion?

> **NB** It would be nice to see some documentation to understand more about the repo.

**Comment by rodluger** [comment]
@mxochicale I'm guessing it's because you're running Python 2? I pushed a fix; can you try again and let me know if it runs?

**Comment by rodluger** [comment]
Ah, and yes: docs (and several improvements) are on my to-do list!

**Comment by rodluger** [comment]
Closing this for now. Feel free to re-open if you're still having issues.

**Comment by mxochicale** [comment]
@rodluger 

Many thanks for fixing the python2 dependencies and for  update of the readme file. I am trying again to build a pdf and just for your information, and perhaps other users, I realised that my machine requires some python dependencies which create some building errors: 
```
$ cortex/tex$ make
# Generate all figures
cd figures;python pretty_function.py
Traceback (most recent call last):
  File "pretty_function.py", line 3, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
Makefile:33: recipe for target 'figures/pretty_function.pdf' failed
make: *** [figures/pretty_function.pdf] Error 1
```
Perhaps, it requires somewhere in the readme somesort of explanation on which depencies are necessary for cor-TeX.  That said, I went into my virtual environment where matplotlib and other python libraries are installed and the makefile has managed to generate the figures. However, there is an warning and error with the class revtex4-1:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./ms.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
(./aastex62.cls
Document Class: aastex62 2017/10/16 Version 6.2/AAS markup document class
(./revtex4-1.cls
Document Class: revtex4-1 2010/07/25/20:33:00 4.1r (http://publish.aps.org/revt
ex4/ for documentation)
ltxutil[2010/07/25/20:33:00 4.1r utilities package (portions licensed from W. E
. Baxter web at superscript.com)]
ltxfront[2010/07/25/20:33:00 4.1r frontmatter package (AO,DPC)]
ltxgrid[2010/07/25/20:33:00 4.1r page grid package (portions licensed from W. E
. Baxter web at superscript.com)]

Class revtex4-1 Warning: No Society specified, using default society aps.


! LaTeX Error: File `aps4-1.rtx' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: rtx)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7543 \@process@society{aps}
                             %^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on ms.log.
Done.
Done.
```

Not sure if I have to update "TeX Live 2017/Debian" in this Ubuntu 18.04 x64  machine. Any comments?
